name: collect_news

on:
  schedule:
    - cron: '0 23 * * *' # 08:00 KST
  workflow_dispatch:

jobs:
  collect_news:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_CLOUD_EMAIL: ${{ secrets.GOOGLE_CLOUD_EMAIL }}
      GOOGLE_CLOUD_SPREADSHEET_URL: ${{ secrets.GOOGLE_CLOUD_SPREADSHEET_URL }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install chromium --with-deps

      - name: Run collect_news.py
        run: |
          python collect_news.py

      - name: Upload football data
        run: |
          gcloud storage cp -r datas/fotmob/$(date +%Y%m%d) gs://my-football-news/football-news/datas/fotmob/$(date +%Y%m%d)
          if [ -d "datas/news_rss/$(date +%Y%m%d)" ]; then
            gcloud storage cp -r datas/news_rss/$(date +%Y%m%d) gs://my-football-news/football-news/datas/news_rss/$(date +%Y%m%d)
          fi